version: '3'

services:

  django:
    build:
      context: .
      dockerfile: Dockerfile-FaceMaskDetector
    ports:
      - "8800:8000"
    volumes:
      - "./media:/webapp/FaceMaskDetector/media"
      - "./static:/webapp/FaceMaskDetector/static"
      - "./db.sqlite3:/webapp/FaceMaskDetector/db.sqlite3"
      - "./Arial.ttf:/root/.config/Ultralytics/Arial.ttf"
    container_name: 'FaceMaskDetect_django'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              
